
version: '3'
services:
    redis:
        image: "redis:alpine"
        ports:
            - 6379:6379
    opensearch:
        image: "opensearch:2.10.0"
        ports:
          - 9200:9200
        environment:
          - node.name=es01
          - discovery.type=single-node
        networks:
          - opensearch
    kibana:
      image: "opensearchproject/opensearch-dashboards:latest"
        container_name: "kibana"
        ports:
          - 5601:5601
        environment:
          ELASTICSEARCH_URL: http://opensearch:9200
          ELASTICSEARCH_HOSTS: http://opensearch:9200
        networks:
          - opensearch
    etherpad:
        image: "etherpad/etherpad"
        ports:
          - 9001:9001
    mail:
        image: "mailhog/mailhog"
        ports:
          - 1025:1025
          - 8025:8025
networks:
  opensearch:
    driver: bridge
