
version: '3'
services:
    redis:
        image: "redis:alpine"
        ports:
            - 6379:6379
    etherpad:
        image: "etherpad/etherpad"
        ports:
          - 9001:9001
    mail:
        image: "mailhog/mailhog"
        ports:
          - 1025:1025
          - 8025:8025
