

less-plone:
	grunt --gruntfile=watchable-grunt.js less-plone

less-plone-logged-in:
	grunt --gruntfile=watchable-grunt.js less-plone-logged-in


js-plone:
	grunt --gruntfile=watchable-grunt.js js-plone

js-plone-logged-in:
	grunt --gruntfile=watchable-grunt.js js-plone-logged-in

js-plone-build:
	grunt --gruntfile=watchable-grunt.js js-plone-build

js-plone-logged-in-build:
	grunt --gruntfile=watchable-grunt.js js-plone-logged-in-build


watch-less-plone:
	python watch-run.py --command="grunt --gruntfile=watchable-grunt.js less-plone" --dirs /opt/plone/src/castle.cms/castle/cms/static/less

watch-less-plone-logged-in:
	python watch-run.py --command="grunt --gruntfile=watchable-grunt.js less-plone-logged-in" --dirs /opt/plone/src/castle.cms/castle/cms/static/less
